// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kafka.proto

/*
Package connect is a generated protocol buffer package.

It is generated from these files:
	kafka.proto

It has these top-level messages:
*/
package connect

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import kafka_scheduler_v1 "github.com/confluentinc/cc-structs/kafka/scheduler/v1"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Kafka service

type KafkaClient interface {
	List(ctx context.Context, in *kafka_scheduler_v1.GetKafkaClustersRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.GetKafkaClustersReply, error)
}

type kafkaClient struct {
	cc *grpc.ClientConn
}

func NewKafkaClient(cc *grpc.ClientConn) KafkaClient {
	return &kafkaClient{cc}
}

func (c *kafkaClient) List(ctx context.Context, in *kafka_scheduler_v1.GetKafkaClustersRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.GetKafkaClustersReply, error) {
	out := new(kafka_scheduler_v1.GetKafkaClustersReply)
	err := grpc.Invoke(ctx, "/connect.Kafka/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Kafka service

type KafkaServer interface {
	List(context.Context, *kafka_scheduler_v1.GetKafkaClustersRequest) (*kafka_scheduler_v1.GetKafkaClustersReply, error)
}

func RegisterKafkaServer(s *grpc.Server, srv KafkaServer) {
	s.RegisterService(&_Kafka_serviceDesc, srv)
}

func _Kafka_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kafka_scheduler_v1.GetKafkaClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KafkaServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Kafka/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KafkaServer).List(ctx, req.(*kafka_scheduler_v1.GetKafkaClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kafka_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connect.Kafka",
	HandlerType: (*KafkaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Kafka_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kafka.proto",
}

func init() { proto.RegisterFile("kafka.proto", fileDescriptorKafka) }

var fileDescriptorKafka = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x4e, 0x4c, 0xcb,
	0x4e, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xce, 0xcf, 0xcb, 0x4b, 0x4d, 0x2e,
	0x91, 0x52, 0x02, 0x8b, 0xea, 0x17, 0x27, 0x67, 0xa4, 0xa6, 0x94, 0xe6, 0xa4, 0x16, 0xe9, 0x97,
	0x19, 0x22, 0x38, 0x10, 0xc5, 0x46, 0x99, 0x5c, 0xac, 0xde, 0x20, 0x55, 0x42, 0x09, 0x5c, 0x2c,
	0x3e, 0x99, 0xc5, 0x25, 0x42, 0xda, 0x7a, 0x10, 0xb3, 0x10, 0x0a, 0xcb, 0x0c, 0xf5, 0xdc, 0x53,
	0x4b, 0xc0, 0xaa, 0x9c, 0x73, 0x4a, 0x8b, 0x4b, 0x52, 0x8b, 0x8a, 0x83, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0xa4, 0x34, 0x89, 0x53, 0x5c, 0x90, 0x53, 0xa9, 0xc4, 0x90, 0xc4, 0x06, 0xb6, 0xd1,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x49, 0xbb, 0xbb, 0xad, 0x00, 0x00, 0x00,
}
