// Code generated by mocker; DO NOT EDIT
// github.com/travisjeffery/mocker
package mock

import (
	orgv1 "github.com/confluentinc/cc-structs/kafka/org/v1"
	"net/http"
	"sync"
)

var (
	lockAPIKeyCreate sync.RWMutex
)

// APIKey is a mock implementation of APIKey.
//
//     func TestSomethingThatUsesAPIKey(t *testing.T) {
//
//         // make and configure a mocked APIKey
//         mockedAPIKey := &APIKey{
//             CreateFunc: func(key *orgv1.ApiKey) (*orgv1.ApiKey, *http.Response, error) {
// 	               panic("TODO: mock out the Create method")
//             },
//         }
//
//         // TODO: use mockedAPIKey in code that requires APIKey
//         //       and then make assertions.
//
//     }
type APIKey struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(key *orgv1.ApiKey) (*orgv1.ApiKey, *http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Key is the key argument value.
			Key *orgv1.ApiKey
		}
	}
}

// Reset resets the calls made to the mocked APIs.
func (mock *APIKey) Reset() {
	lockAPIKeyCreate.Lock()
	mock.calls.Create = nil
	lockAPIKeyCreate.Unlock()
}

// Create calls CreateFunc.
func (mock *APIKey) Create(key *orgv1.ApiKey) (*orgv1.ApiKey, *http.Response, error) {
	if mock.CreateFunc == nil {
		panic("moq: APIKey.CreateFunc is nil but APIKey.Create was just called")
	}
	callInfo := struct {
		Key *orgv1.ApiKey
	}{
		Key: key,
	}
	lockAPIKeyCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockAPIKeyCreate.Unlock()
	return mock.CreateFunc(key)
}

// CreateCalled returns true if at least one call was made to Create.
func (mock *APIKey) CreateCalled() bool {
	lockAPIKeyCreate.RLock()
	defer lockAPIKeyCreate.RUnlock()
	return len(mock.calls.Create) > 0
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedAPIKey.CreateCalls())
func (mock *APIKey) CreateCalls() []struct {
	Key *orgv1.ApiKey
} {
	var calls []struct {
		Key *orgv1.ApiKey
	}
	lockAPIKeyCreate.RLock()
	calls = mock.calls.Create
	lockAPIKeyCreate.RUnlock()
	return calls
}
