// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: connect.proto

/*
Package connect is a generated protocol buffer package.

It is generated from these files:
	connect.proto

It has these top-level messages:
*/
package connect

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import kafka_scheduler_v1 "github.com/confluentinc/cc-structs/kafka/scheduler/v1"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Connect service

type ConnectClient interface {
	List(ctx context.Context, in *kafka_scheduler_v1.GetConnectClustersRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.GetConnectClustersReply, error)
	Describe(ctx context.Context, in *kafka_scheduler_v1.GetConnectClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.GetConnectClusterReply, error)
	DescribeS3Sink(ctx context.Context, in *kafka_scheduler_v1.GetConnectS3SinkClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.GetConnectS3SinkClusterReply, error)
	CreateS3Sink(ctx context.Context, in *kafka_scheduler_v1.CreateConnectS3SinkClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.CreateConnectS3SinkClusterReply, error)
	UpdateS3Sink(ctx context.Context, in *kafka_scheduler_v1.UpdateConnectS3SinkClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.UpdateConnectS3SinkClusterReply, error)
	Delete(ctx context.Context, in *kafka_scheduler_v1.DeleteConnectClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.DeleteConnectClusterReply, error)
}

type connectClient struct {
	cc *grpc.ClientConn
}

func NewConnectClient(cc *grpc.ClientConn) ConnectClient {
	return &connectClient{cc}
}

func (c *connectClient) List(ctx context.Context, in *kafka_scheduler_v1.GetConnectClustersRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.GetConnectClustersReply, error) {
	out := new(kafka_scheduler_v1.GetConnectClustersReply)
	err := grpc.Invoke(ctx, "/connect.Connect/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) Describe(ctx context.Context, in *kafka_scheduler_v1.GetConnectClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.GetConnectClusterReply, error) {
	out := new(kafka_scheduler_v1.GetConnectClusterReply)
	err := grpc.Invoke(ctx, "/connect.Connect/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) DescribeS3Sink(ctx context.Context, in *kafka_scheduler_v1.GetConnectS3SinkClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.GetConnectS3SinkClusterReply, error) {
	out := new(kafka_scheduler_v1.GetConnectS3SinkClusterReply)
	err := grpc.Invoke(ctx, "/connect.Connect/DescribeS3Sink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) CreateS3Sink(ctx context.Context, in *kafka_scheduler_v1.CreateConnectS3SinkClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.CreateConnectS3SinkClusterReply, error) {
	out := new(kafka_scheduler_v1.CreateConnectS3SinkClusterReply)
	err := grpc.Invoke(ctx, "/connect.Connect/CreateS3Sink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) UpdateS3Sink(ctx context.Context, in *kafka_scheduler_v1.UpdateConnectS3SinkClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.UpdateConnectS3SinkClusterReply, error) {
	out := new(kafka_scheduler_v1.UpdateConnectS3SinkClusterReply)
	err := grpc.Invoke(ctx, "/connect.Connect/UpdateS3Sink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) Delete(ctx context.Context, in *kafka_scheduler_v1.DeleteConnectClusterRequest, opts ...grpc.CallOption) (*kafka_scheduler_v1.DeleteConnectClusterReply, error) {
	out := new(kafka_scheduler_v1.DeleteConnectClusterReply)
	err := grpc.Invoke(ctx, "/connect.Connect/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Connect service

type ConnectServer interface {
	List(context.Context, *kafka_scheduler_v1.GetConnectClustersRequest) (*kafka_scheduler_v1.GetConnectClustersReply, error)
	Describe(context.Context, *kafka_scheduler_v1.GetConnectClusterRequest) (*kafka_scheduler_v1.GetConnectClusterReply, error)
	DescribeS3Sink(context.Context, *kafka_scheduler_v1.GetConnectS3SinkClusterRequest) (*kafka_scheduler_v1.GetConnectS3SinkClusterReply, error)
	CreateS3Sink(context.Context, *kafka_scheduler_v1.CreateConnectS3SinkClusterRequest) (*kafka_scheduler_v1.CreateConnectS3SinkClusterReply, error)
	UpdateS3Sink(context.Context, *kafka_scheduler_v1.UpdateConnectS3SinkClusterRequest) (*kafka_scheduler_v1.UpdateConnectS3SinkClusterReply, error)
	Delete(context.Context, *kafka_scheduler_v1.DeleteConnectClusterRequest) (*kafka_scheduler_v1.DeleteConnectClusterReply, error)
}

func RegisterConnectServer(s *grpc.Server, srv ConnectServer) {
	s.RegisterService(&_Connect_serviceDesc, srv)
}

func _Connect_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kafka_scheduler_v1.GetConnectClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).List(ctx, req.(*kafka_scheduler_v1.GetConnectClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kafka_scheduler_v1.GetConnectClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).Describe(ctx, req.(*kafka_scheduler_v1.GetConnectClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_DescribeS3Sink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kafka_scheduler_v1.GetConnectS3SinkClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).DescribeS3Sink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/DescribeS3Sink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).DescribeS3Sink(ctx, req.(*kafka_scheduler_v1.GetConnectS3SinkClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_CreateS3Sink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kafka_scheduler_v1.CreateConnectS3SinkClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).CreateS3Sink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/CreateS3Sink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).CreateS3Sink(ctx, req.(*kafka_scheduler_v1.CreateConnectS3SinkClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_UpdateS3Sink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kafka_scheduler_v1.UpdateConnectS3SinkClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).UpdateS3Sink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/UpdateS3Sink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).UpdateS3Sink(ctx, req.(*kafka_scheduler_v1.UpdateConnectS3SinkClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kafka_scheduler_v1.DeleteConnectClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).Delete(ctx, req.(*kafka_scheduler_v1.DeleteConnectClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Connect_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connect.Connect",
	HandlerType: (*ConnectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Connect_List_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Connect_Describe_Handler,
		},
		{
			MethodName: "DescribeS3Sink",
			Handler:    _Connect_DescribeS3Sink_Handler,
		},
		{
			MethodName: "CreateS3Sink",
			Handler:    _Connect_CreateS3Sink_Handler,
		},
		{
			MethodName: "UpdateS3Sink",
			Handler:    _Connect_UpdateS3Sink_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Connect_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connect.proto",
}

func init() { proto.RegisterFile("connect.proto", fileDescriptorConnect) }

var fileDescriptorConnect = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4e, 0x85, 0x30,
	0x10, 0x40, 0x5d, 0xe8, 0xff, 0xa6, 0x51, 0x17, 0x5d, 0xb2, 0x64, 0xa9, 0x52, 0x04, 0xe2, 0x09,
	0x20, 0x71, 0xe3, 0x4a, 0xe2, 0x01, 0xa0, 0x0c, 0x11, 0x69, 0x00, 0xdb, 0x81, 0x68, 0xe2, 0xc5,
	0xbc, 0x9d, 0x09, 0x03, 0x92, 0x18, 0xc2, 0x2f, 0xcb, 0x49, 0xdf, 0x9b, 0xb7, 0xe8, 0xb0, 0x6b,
	0xd9, 0x36, 0x0d, 0x48, 0x14, 0x9d, 0x6e, 0xb1, 0xe5, 0xc7, 0x69, 0x74, 0xdc, 0x3a, 0x2b, 0xeb,
	0xcc, 0x37, 0xf2, 0x0d, 0x8a, 0x5e, 0x81, 0xf6, 0x87, 0x60, 0x19, 0x08, 0x0e, 0x7f, 0x2e, 0xd8,
	0x31, 0x26, 0x9e, 0x17, 0xec, 0xfc, 0xb9, 0x32, 0xc8, 0x3d, 0x31, 0x8a, 0x62, 0x61, 0x87, 0x40,
	0x3c, 0x01, 0x4e, 0x5c, 0xac, 0x7a, 0x83, 0xa0, 0xcd, 0x0b, 0x7c, 0xf4, 0x60, 0xd0, 0xb9, 0xb3,
	0xc5, 0x3b, 0xf5, 0xe5, 0x9e, 0xf1, 0x92, 0x5d, 0x26, 0x60, 0xa4, 0xae, 0x72, 0xe0, 0xf7, 0x56,
	0xea, 0x1c, 0xba, 0xb5, 0xa4, 0xa9, 0xf3, 0xc9, 0x6e, 0xe6, 0x4e, 0x1a, 0xa5, 0x55, 0x53, 0xf3,
	0x70, 0xdb, 0x27, 0xea, 0x5f, 0xf3, 0x61, 0x97, 0x43, 0xe5, 0x6f, 0x76, 0x15, 0x6b, 0xc8, 0x70,
	0xee, 0x3e, 0xae, 0xed, 0x20, 0x62, 0x2b, 0x1d, 0xed, 0xd5, 0xfe, 0xea, 0xaf, 0x5d, 0x71, 0xa2,
	0x4e, 0xc4, 0xee, 0xfa, 0x96, 0x46, 0xf5, 0x77, 0x76, 0x48, 0x40, 0x01, 0x02, 0xf7, 0xd7, 0x16,
	0xd0, 0xdb, 0xfa, 0xf7, 0x7a, 0xf6, 0xc2, 0xd8, 0xca, 0x0f, 0xe3, 0x09, 0x47, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0x29, 0xeb, 0xc8, 0x00, 0x03, 0x00, 0x00,
}
