// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	v1 "github.com/confluentinc/ccloudapis/org/v1"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0x84, 0x21,
	0x10, 0xc7, 0x3b, 0x7c, 0x45, 0x78, 0x94, 0x4e, 0x7b, 0xa9, 0xf6, 0x18, 0xa1, 0x6c, 0xfb, 0x04,
	0xd1, 0x42, 0x97, 0x88, 0x28, 0xf6, 0x01, 0xf6, 0x9b, 0x9d, 0x36, 0xc1, 0xd4, 0x74, 0x14, 0xba,
	0xf6, 0xe4, 0xe1, 0xca, 0x7e, 0x11, 0x99, 0x78, 0x52, 0xf0, 0x37, 0xff, 0x9f, 0x33, 0x0c, 0x63,
	0x31, 0xa0, 0x17, 0xce, 0x5b, 0xb2, 0x7c, 0xc8, 0xf7, 0xd9, 0x72, 0xa7, 0xe8, 0x2d, 0x8e, 0x02,
	0xec, 0xbb, 0x04, 0x6b, 0x5e, 0x75, 0x44, 0x43, 0xca, 0x80, 0x04, 0xd0, 0x36, 0x6e, 0x37, 0x4e,
	0x05, 0x69, 0xfd, 0x4e, 0xa6, 0x45, 0x3e, 0x4a, 0xe9, 0xcd, 0xd7, 0x31, 0x1b, 0xd6, 0x01, 0x3d,
	0x4f, 0xec, 0xec, 0xce, 0xe3, 0x86, 0xf0, 0x05, 0x7d, 0x52, 0x80, 0xb7, 0x00, 0x36, 0x1a, 0xe2,
	0x42, 0xfc, 0x94, 0x8b, 0x5c, 0x97, 0x16, 0xa2, 0x06, 0x3e, 0xe3, 0x47, 0xc4, 0x40, 0xb3, 0xeb,
	0x6e, 0xde, 0xe9, 0xcf, 0xf9, 0x51, 0xf6, 0xae, 0x50, 0x63, 0x97, 0xb7, 0x06, 0xb6, 0xbc, 0x75,
	0xbe, 0x78, 0x1d, 0xe3, 0xf7, 0x48, 0xbf, 0xdf, 0x02, 0xaf, 0xa5, 0xfc, 0xc5, 0x0e, 0xce, 0xab,
	0x4e, 0x7a, 0xea, 0x74, 0xed, 0xb6, 0x7d, 0x13, 0xae, 0x81, 0xad, 0x4e, 0xeb, 0x7c, 0xf1, 0x3e,
	0xb1, 0xd3, 0x15, 0x06, 0xf0, 0x6a, 0x44, 0x7e, 0x59, 0xff, 0x71, 0xde, 0x80, 0x43, 0xfc, 0x79,
	0x0b, 0x29, 0x89, 0x8f, 0x6c, 0x78, 0x50, 0x81, 0xf8, 0xfc, 0x7f, 0x74, 0x9a, 0xd1, 0x45, 0x93,
	0xd9, 0xe7, 0x8d, 0x27, 0xfb, 0x5d, 0x5c, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x87, 0xfa, 0x4f,
	0xe8, 0xd4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	CreateServiceAccount(ctx context.Context, in *v1.CreateServiceAccountRequest, opts ...grpc.CallOption) (*v1.CreateServiceAccountReply, error)
	DeleteServiceAccount(ctx context.Context, in *v1.DeleteServiceAccountRequest, opts ...grpc.CallOption) (*v1.DeleteServiceAccountReply, error)
	GetServiceAccounts(ctx context.Context, in *v1.GetServiceAccountsRequest, opts ...grpc.CallOption) (*v1.GetServiceAccountsReply, error)
	UpdateServiceAccount(ctx context.Context, in *v1.UpdateServiceAccountRequest, opts ...grpc.CallOption) (*v1.UpdateServiceAccountReply, error)
	Describe(ctx context.Context, in *v1.GetUserRequest, opts ...grpc.CallOption) (*v1.GetUserReply, error)
	List(ctx context.Context, in *v1.GetUsersRequest, opts ...grpc.CallOption) (*v1.GetUsersReply, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) CreateServiceAccount(ctx context.Context, in *v1.CreateServiceAccountRequest, opts ...grpc.CallOption) (*v1.CreateServiceAccountReply, error) {
	out := new(v1.CreateServiceAccountReply)
	err := c.cc.Invoke(ctx, "/user.User/CreateServiceAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteServiceAccount(ctx context.Context, in *v1.DeleteServiceAccountRequest, opts ...grpc.CallOption) (*v1.DeleteServiceAccountReply, error) {
	out := new(v1.DeleteServiceAccountReply)
	err := c.cc.Invoke(ctx, "/user.User/DeleteServiceAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetServiceAccounts(ctx context.Context, in *v1.GetServiceAccountsRequest, opts ...grpc.CallOption) (*v1.GetServiceAccountsReply, error) {
	out := new(v1.GetServiceAccountsReply)
	err := c.cc.Invoke(ctx, "/user.User/GetServiceAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateServiceAccount(ctx context.Context, in *v1.UpdateServiceAccountRequest, opts ...grpc.CallOption) (*v1.UpdateServiceAccountReply, error) {
	out := new(v1.UpdateServiceAccountReply)
	err := c.cc.Invoke(ctx, "/user.User/UpdateServiceAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Describe(ctx context.Context, in *v1.GetUserRequest, opts ...grpc.CallOption) (*v1.GetUserReply, error) {
	out := new(v1.GetUserReply)
	err := c.cc.Invoke(ctx, "/user.User/Describe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) List(ctx context.Context, in *v1.GetUsersRequest, opts ...grpc.CallOption) (*v1.GetUsersReply, error) {
	out := new(v1.GetUsersReply)
	err := c.cc.Invoke(ctx, "/user.User/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	CreateServiceAccount(context.Context, *v1.CreateServiceAccountRequest) (*v1.CreateServiceAccountReply, error)
	DeleteServiceAccount(context.Context, *v1.DeleteServiceAccountRequest) (*v1.DeleteServiceAccountReply, error)
	GetServiceAccounts(context.Context, *v1.GetServiceAccountsRequest) (*v1.GetServiceAccountsReply, error)
	UpdateServiceAccount(context.Context, *v1.UpdateServiceAccountRequest) (*v1.UpdateServiceAccountReply, error)
	Describe(context.Context, *v1.GetUserRequest) (*v1.GetUserReply, error)
	List(context.Context, *v1.GetUsersRequest) (*v1.GetUsersReply, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_CreateServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/CreateServiceAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateServiceAccount(ctx, req.(*v1.CreateServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/DeleteServiceAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteServiceAccount(ctx, req.(*v1.DeleteServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetServiceAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetServiceAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetServiceAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetServiceAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetServiceAccounts(ctx, req.(*v1.GetServiceAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/UpdateServiceAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateServiceAccount(ctx, req.(*v1.UpdateServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Describe(ctx, req.(*v1.GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).List(ctx, req.(*v1.GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServiceAccount",
			Handler:    _User_CreateServiceAccount_Handler,
		},
		{
			MethodName: "DeleteServiceAccount",
			Handler:    _User_DeleteServiceAccount_Handler,
		},
		{
			MethodName: "GetServiceAccounts",
			Handler:    _User_GetServiceAccounts_Handler,
		},
		{
			MethodName: "UpdateServiceAccount",
			Handler:    _User_UpdateServiceAccount_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _User_Describe_Handler,
		},
		{
			MethodName: "List",
			Handler:    _User_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
